### ISSUE TITLE
set correct orientation on hover menu item for seperator

### ISSUE THREAD

**Issue by bertonbeil** [bertonbeil/wplBertonbeil#4]
if hover work rotate to it if in more rotate to it

**Comment by bertonbeil** [comment]
@nizkeit for add this feature create new branch then push work wersion to master

**Comment by bertonbeil** [comment]
@nizkeit one more think

Write your script in main.js file
Rememberyour write your code in `.ready()` function:
```
$(document).ready(function() {
  // your code here
});
```
or shorter 
```
$(function() {
  // your code here
});
```

**Comment by ghost** [comment]
soon optimize this code :)
