### ISSUE TITLE
sass

### ISSUE THREAD

**Issue by bertonbeil** [bertonbeil/wplBertonbeil#6]
Configure sass compiler
Install sass

- [x] Install sass

- [x] Install compass `$gem install compass`

- [x] For render using `$compass watch`

**Comment by ghost** [comment]
send me, please guides
http://sass-lang.com/ - like that

**Comment by bertonbeil** [comment]
this very bacis thinks so look here http://compass-style.org/help/
all that you must do(guide from me):

- Open ruby cmd and install compass and sass `$gem install sass` and `$gem install compass`
- Create empty folder and open ruby cmd on it or show route using `cd <your directory name>`
- If you already in test folder type next `$gem compass init`
- Look on files created in folder sass and css folders
- Find file config.rb and open it 
```
#Set this to the root of your project when deployed:
http_path = "/"
css_dir = "css"
sass_dir = "sass"
images_dir = "img"
javascripts_dir = "js"
```
- Here you can change default setings I show you mine configurations
- You must understand all files from sass (somestyle.scss) will compiled into css folder
- You can delete all files from sass and create own

### Remember for run compeller you must use `$gem compass watch` in project folder

Good luck!
